version: '3.8'

services:
  nba-service:
    image: nba-service:latest
    container_name: nba-service
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - DB_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - DB_DATASOURCE_USERNAME=user
      - DB_DATASOURCE_PASSWORD=password

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@mail.com
      PGADMIN_DEFAULT_PASSWORD: password
