version: '3.8'

services:
  nba-service1:
    image: nba-service:latest
    container_name: nba-service1
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      - DB_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - DB_DATASOURCE_USERNAME=user
      - DB_DATASOURCE_PASSWORD=password

  nba-service2:
    image: nba-service:latest
    container_name: nba-service2
    depends_on:
      - postgres
    ports:
      - "8082:8080"
    environment:
      - DB_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - DB_DATASOURCE_USERNAME=user
      - DB_DATASOURCE_PASSWORD=password

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@mail.com
      PGADMIN_DEFAULT_PASSWORD: password

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

